### ISSUE TITLE
Hacker Route 2 wrong password

### ISSUE THREAD

**Issue by Elijah1111** [FedX-sudo/Dr460nized#12]
I just noticed that Hackerroute 2 I got a password that was 5010, but the directions said it should be between 0 and 99

**Comment by Elijah1111** [comment]
Looks like it is just set to 5010 in dntos/__init__.py line 92, I would recommend setting it to a random integer from 0-99 so it matches the directions.

**Comment by Dmytr000** [comment]
Fixed it.
