### ISSUE TITLE
Exit Status 1

### ISSUE THREAD

**Issue by FedX-sudo** [FedX-sudo/Dr460nized#2]
This is probably either a Pygame issue or an issue in the way I reworked the code in my local repo, but there could be a workaround if anyone knows about such things. That said, when closing a Pygame window KDE Plasma sends a signit signal to Pygame, which results in an exist status 1. In short, closing the window crashes Python. I have an STrace log if anyone feels like digging through 53,417 lines of logfile. I will also commit my refactor into a development branch soon. Thanks!

**Comment by Elijah1111** [comment]
This might help for catching the siginit signal: https://stackoverflow.com/questions/1112343/how-do-i-capture-sigint-in-python

**Comment by Elijah1111** [comment]
And the Signals library: https://docs.python.org/3/library/signal.html
It might also prove useful

**Comment by FedX-sudo** [comment]
Ok, I tested the recently updated UI branch in an attempt to merge it into Main, this issue has been solved... somehow?
