### ISSUE TITLE
Terminal Emulator

### ISSUE THREAD

**Issue by Elijah1111** [FedX-sudo/Dr460nized#4]
Implement the terminal emulator

**Comment by FedX-sudo** [comment]
Ok, I have ls emulation working. I am using a Unix file layout, if that works for everyone, and am wondering what the username should be. Perhaps *Muffin-Man* although straight *root* could be simpler? 

For file system emulation I am using a list of folders IE  `fs = ['/', '/home/']` and for removing directories I was thinking of popping an item out of the array, but I am not sure if Python will remember that or if it will garbage collect the fs variable out of memory the moment you are done calling on the array. This is not an issue yet, but it probably will be, so if anyone has thoughts regarding file system emulation, could you let me know?

**Comment by Elijah1111** [comment]
So you could just pop the array, depending on your implementation it might be that you need the fs array to be a class variable or a global variable so that it maintains its contents.

**Comment by FedX-sudo** [comment]
This has been solved by using a toml file.
